### ISSUE TITLE
Other LPs usually have Stunnel as the encryption layer. How does FXCM make the connection secure?

### ISSUE THREAD

**Issue by fintechee** [fxcm/FIXAPI#4]
Hi FXCM,

Other LPs usually have Stunnel as the encryption layer.
Without it, all the data are exposed to the sniffers.
But FXCM seems not using Stunnel.
Please tell me how to make the connection secure.
Many thanks.

Best Regards,
Fintechee

**Comment by ghost** [comment]
FXCM do have stunnle
please send mail request to api@fxcm.com for detail information.
